# Generated by Django 4.1.1 on 2022-09-26 02:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Hashtag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'verbose_name': '해시태그',
                'verbose_name_plural': '해시태그 목록',
                'db_table': 'hashtag',
            },
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('like_num', models.PositiveIntegerField(verbose_name='좋아요 수')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='좋아요 한 날짜')),
            ],
            options={
                'verbose_name': '좋아요',
                'verbose_name_plural': '좋아요 목록',
                'db_table': 'like',
            },
        ),
        migrations.CreateModel(
            name='Posting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=72, verbose_name='제목')),
                ('content', models.TextField(verbose_name='내용')),
                ('hits', models.PositiveIntegerField(default=0, verbose_name='조회수')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='게시글 생성 날짜')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='게시글 수정 날짜')),
                ('is_delete', models.BooleanField(default=0, verbose_name='삭제 여부')),
                ('hashtag', models.ManyToManyField(db_column='hashtag_id', to='postings.hashtag')),
                ('likes', models.ManyToManyField(blank=True, related_name='posting_likes', through='postings.Like', to=settings.AUTH_USER_MODEL, verbose_name='좋아요 내역')),
                ('user_id', models.ForeignKey(db_column='user_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='postings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '게시글',
                'verbose_name_plural': '게시글 목록',
                'db_table': 'posting',
            },
        ),
        migrations.AddField(
            model_name='like',
            name='post_id',
            field=models.ForeignKey(db_column='post_id', on_delete=django.db.models.deletion.CASCADE, to='postings.posting'),
        ),
        migrations.AddField(
            model_name='like',
            name='user_id',
            field=models.ForeignKey(db_column='user_id', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='like',
            unique_together={('user_id', 'post_id')},
        ),
    ]
