# Generated by Django 4.1.1 on 2022-09-27 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('postings', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='like_num',
        ),
    ]
