# Generated by Django 4.1.1 on 2022-09-28 04:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('postings', '0002_remove_like_like_num'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='like',
            unique_together=set(),
        ),
    ]
