# Generated by Django 4.1.1 on 2022-09-29 06:20

import apps.postings.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postings', '0003_alter_like_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hashtag',
            name='name',
            field=models.CharField(max_length=150, unique=True, validators=[apps.postings.validators.validate_hashtag_name]),
        ),
    ]
