# Generated by Django 4.1.1 on 2022-09-29 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postings', '0004_alter_hashtag_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hashtag',
            name='name',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
